#!/bin/bash

stamp=$(date +%Y%m%d-%H%M)
file="plan-${stamp}"

terraform plan -out=${file}

if [[ $? -eq 0 ]]; then
  echo
  echo "SUCCESS: Wrote plan file, ${file}"
  cp .lastplan .prevplan
  echo ${file} > .lastplan
fi
